### ISSUE TITLE
Make data available only to people you follow?

### ISSUE THREAD

**Issue by TheExGenesis** [TheExGenesis/community-archive#10]
People (like me) might be antsy to make their archives fully public. Personally I'd be okay with it being public to people I follow. I would also be okay with delegating my trust to a few friends and opening up my archive to people they follow.

Might fragment the data too much if users feel sheepish. I wonder what people think.

**Comment by DefenderOfBasic** [comment]
I think this is critical for the long term growth of this project & the bigger theme of user ownership of data. I'm undecided on whether we want this (1) supported first class in the archive server and/or (2) part of the server settings itself if you're self hosting. Like, the same way Mastodon allows you to enable sign ups from the public, or close it to invite only. 

Do people want to upload to the public archive but have it only accessible to a few other users? Or is it better to upload to their own private archive? It may be easier for the maintainers of the public archive if we assume everything that comes to us is public, and support people in setting up their own servers for privacy reasons?

**Comment by DefenderOfBasic** [comment]
Our current stance is, we do want to support this long term, we're not sure yet what form it's going to take. I think we decided recently in the Discord that we should remove the "keep private" option, everything in the CA is public by default. We can have a more robust solution for this later on, or the solution for that could be people self-hosting a version of CA for specific communities?

same way people self host Mastodon instances and can make them public or private.

(@TheExGenesis I'm inclined to close this since there's no specific action we want to do here sort term?)

**Comment by TheExGenesis** [comment]
yes sounds good!
