### ISSUE TITLE
Integrate with Tweetback? 

### ISSUE THREAD

**Issue by OmarShehata** [TheExGenesis/community-archive#2]
See: https://github.com/tweetback/tweetback

A lot of people are self hosting their own twitter archive through this. For example, bmann: https://twitter.bmannconsulting.com/

See: https://x.com/bmann/status/1816363630671323513

it might be cool to somehow integrate this data. To start with, could be just linking to it (so that we start to collect a list of everyone who has shared their twitter archives publicly)

**Comment by TheExGenesis** [comment]
I'm not sure I understand, is tweetback a front-end for archives?

**Comment by OmarShehata** [comment]
I think it also is just making me think about like, is there a way for people who want to self host their archive to still be part of this movement/collective.

**Comment by DefenderOfBasic** [comment]
Closing this because no actionable proposal here. I think the intention here is part of a larger theme of "self hosting" which we do want to make as easy as possible (it's good for us & the community, takes pressure off any central point of failure, etc). 

we have a plan here to make the raw data available on a CDN/cache, which means if tools like Tweetback want to consume the content they totally could: https://github.com/TheExGenesis/community-archive/issues/72
